### ISSUE TITLE
6.0 Update

### ISSUE THREAD

**Issue by DenL** [aers/EnemyListDebuffs#3]
Godsend for debuff management. Hope it gets updated soon!

**Comment by doomsz** [comment]
waiting for this one aswell

**Comment by soonerrob** [comment]
same!

**Comment by kalilistic** [comment]
any update?

**Comment by slotthhy** [comment]
My MOAction isn't working. Please help

**Comment by LawNO** [comment]
Extremely useful addon, could it be updated to 6.0 pretty pls?

**Comment by Metalslugsc** [comment]
Total gamechanger in dungeons to track which mobs you have DoTs on.
Please Update

**Comment by soonerrob** [comment]
Guys just install DelvUI via Dalamud... Its amazing.. has its own enemy list with a massive amount of customization. You can enable/disable any and all of DelvUI.. you could just use the ememy list if you want.  I'm only posting this here because there has been no response. So..

**Comment by thisnameistoolo** [comment]
> Guys just install DelvUI via Dalamud... Its amazing.. has its own enemy list with a massive amount of customization. You can enable/disable any and all of DelvUI.. you could just use the ememy list if you want. I'm only posting this here because there has been no response. So..

The thing I don't like about DelvUI is that it has caused crashing for me in the past and I don't want to risk dealing with queues any more than necessary.

That, and I find it very ugly and jarring.

**Comment by soonerrob** [comment]
I haven't had any crashing with it.. I also tried it in the past and went away from it, but that was before I realized that you can enable/disable all of the UI elements that it includes.. But functionally it has the 3 things that I use Dalamud plugins for that are ALL disabled.. Customizable Party List, Customizable Enemy List and Mouseover Casting.  You can make the Enemy List look however you want to an extent, I get the "ugly" part, but it's working and the Enemylist plugin isn't and I really don't want to wait any longer to see my debuffs and timers.  It's replace the 3 plugins that I have been waiting to get updated.

**Comment by soonerrob** [comment]
> > Guys just install DelvUI via Dalamud... Its amazing.. has its own enemy list with a massive amount of customization. You can enable/disable any and all of DelvUI.. you could just use the ememy list if you want. I'm only posting this here because there has been no response. So..
> 
> The thing I don't like about DelvUI is that it has caused crashing for me in the past and I don't want to risk dealing with queues any more than necessary.
> 
> That, and I find it very ugly and jarring.

I haven't had any crashing with it.. I also tried it in the past and went away from it, but that was before I realized that you can enable/disable all of the UI elements that it includes.. But functionally it has the 3 things that I use Dalamud plugins for that are ALL disabled.. Customizable Party List, Customizable Enemy List and Mouseover Casting.. those are the only things I have enabled and am using stock UI for everything else.. You can make the Enemy List look however you want to an extent, I get the "ugly" part, but it's working and the Enemylist plugin isn't and I really don't want to wait any longer to see my debuffs and timers. It's replace the 3 plugins that I have been waiting to get updated.

**Comment by DenL** [comment]
Closing this because this isn’t a forum….
